# Generated by Django 4.0.2 on 2022-05-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ample', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
