# Generated by Django 4.0.2 on 2022-05-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ample', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
