# Generated by Django 4.0.2 on 2022-05-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ample', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
