# Generated by Django 4.0.2 on 2022-05-31 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ample', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DeliveryMethod',
            field=models.CharField(choices=[('Delivery with Cooler', 'DELIVERY WITH COOLER'), ('Normal Delivery', 'NORMAL DELIVERY')], max_length=50),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('Price', models.FloatField()),
                ('Description', models.CharField(max_length=50, null=True)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ample.order')),
            ],
        ),
    ]
