# Generated by Django 4.0.2 on 2022-06-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ample', '0009_reciver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED')], default='Pending', max_length=50),
        ),
    ]
