# Generated by Django 4.0.2 on 2022-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ample', '0012_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='Status',
            field=models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Pending', 'PENDING'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED')], default='Pending', max_length=50),
        ),
    ]
