# Generated by Django 4.0.2 on 2022-06-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ample', '0013_driver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED'), ('Accepted', 'ACCEPTED')], default='Pending', max_length=50),
        ),
    ]
