# Generated by Django 4.0.2 on 2022-06-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ample', '0015_item_paymentmehtod_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='UserType',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('Customer', 'CUSTOMER'), ('Driver', 'DRIVER'), ('Guest', 'GUEST')], max_length=50),
        ),
    ]
