# Generated by Django 4.0.2 on 2022-07-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ample', '0016_alter_userprofile_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('States', models.CharField(max_length=100)),
                ('Charges', models.FloatField()),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
