# Generated by Django 4.0.2 on 2022-07-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ample', '0017_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Charges',
            field=models.FloatField(default=0),
        ),
    ]
