# Generated by Django 4.0.2 on 2022-07-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ample', '0018_order_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED'), ('Accepted', 'ACCEPTED'), ('Reassigned', 'REASSIGNED')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Reassign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Pending', 'PENDING'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED')], default='Pending', max_length=50)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ample.order')),
            ],
        ),
    ]
